package ollama

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// ollamaLiveAddr is the TCP address used to probe for a local Ollama instance.
const ollamaLiveAddr = "localhost:11434"

// ollamaLiveURL is the generate endpoint for a local Ollama instance.
const ollamaLiveURL = "http://localhost:11434/api/generate"

// ollamaLiveModel is the model to use for live caption tests.
var ollamaLiveModel = func() string {
	if m := os.Getenv("OLLAMA_TEST_MODEL"); m != "" {
		return m
	}
	return "gemma4:26b"
}()

// sampleImagesPath points to the shared test sample directory.
var sampleImagesPath = filepath.Join("..", "..", "..", "..", "assets", "samples")

// skipIfOllamaUnavailable skips the test if no Ollama instance is reachable.
func skipIfOllamaUnavailable(t *testing.T) {
	t.Helper()
	if _, err := net.DialTimeout("tcp", ollamaLiveAddr, 3*time.Second); err != nil {
		t.Skipf("skipping live Ollama test: %v", err)
	}
}

// loadSampleImageBase64 reads a sample image file and returns its base64 encoding.
func loadSampleImageBase64(t *testing.T, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(sampleImagesPath, name))
	if err != nil {
		t.Fatalf("could not read sample image %q: %v", name, err)
	}
	return base64.StdEncoding.EncodeToString(data)
}

// ollamaGenerateRequest is a minimal Ollama /api/generate request body.
type ollamaGenerateRequest struct {
	Model   string   `json:"model"`
	Prompt  string   `json:"prompt"`
	Images  []string `json:"images,omitempty"`
	Think   *bool    `json:"think,omitempty"`
	Stream  bool     `json:"stream"`
	Options struct {
		Temperature float64 `json:"temperature,omitempty"`
	} `json:"options,omitempty"`
}

// callOllamaGenerate sends a request to the local Ollama generate endpoint and
// returns the decoded Response.
func callOllamaGenerate(t *testing.T, req ollamaGenerateRequest) *Response {
	t.Helper()
	req.Stream = false

	body, err := json.Marshal(req)
	if err != nil {
		t.Fatalf("marshal request: %v", err)
	}

	resp, err := http.Post(ollamaLiveURL, "application/json", bytes.NewReader(body)) //nolint:noctx
	if err != nil {
		t.Fatalf("POST %s: %v", ollamaLiveURL, err)
	}
	defer resp.Body.Close()

	var result Response
	if err = json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	return &result
}

// TestLiveOllama_CaptionNoThinkTokens verifies that captions generated by the
// configured live Ollama model do not contain raw <think> tokens.
func TestLiveOllama_CaptionNoThinkTokens(t *testing.T) {
	skipIfOllamaUnavailable(t)

	const captionPrompt = "Create a caption with exactly one sentence in the active voice that describes the main visual content. Begin with the main subject and clear action. Avoid text formatting, meta-language, and filler words."

	images := []string{
		"cat_224.jpeg",
		"chameleon_lime.jpg",
	}

	t.Run("WithoutThink", func(t *testing.T) {
		for _, img := range images {
			t.Run(img, func(t *testing.T) {
				b64 := loadSampleImageBase64(t, img)
				result := callOllamaGenerate(t, ollamaGenerateRequest{
					Model:  ollamaLiveModel,
					Prompt: captionPrompt,
					Images: []string{b64},
				})

				t.Logf("response: %q", result.Response)
				t.Logf("thinking: %q", result.Thinking[:min(len(result.Thinking), 120)])

				if result.Response == "" {
					t.Error("expected non-empty response field")
				}
				if strings.Contains(result.Response, "<think>") || strings.Contains(result.Response, "</think>") {
					t.Errorf("response contains <think> tags: %q", result.Response)
				}
				if strings.Contains(result.Thinking, "<think>") || strings.Contains(result.Thinking, "</think>") {
					t.Errorf("thinking field contains <think> tags: %q", result.Thinking[:min(len(result.Thinking), 200)])
				}
			})
		}
	})

	t.Run("WithThinkTrue", func(t *testing.T) {
		for _, img := range images {
			t.Run(img, func(t *testing.T) {
				b64 := loadSampleImageBase64(t, img)
				thinkTrue := true
				result := callOllamaGenerate(t, ollamaGenerateRequest{
					Model:  ollamaLiveModel,
					Prompt: captionPrompt,
					Images: []string{b64},
					Think:  &thinkTrue,
				})

				t.Logf("response: %q", result.Response)
				t.Logf("thinking (first 120): %q", result.Thinking[:min(len(result.Thinking), 120)])

				if result.Response == "" {
					t.Error("expected non-empty response field when think:true; thinking field would become caption fallback")
				}
				if strings.Contains(result.Response, "<think>") || strings.Contains(result.Response, "</think>") {
					t.Errorf("response contains <think> tags: %q", result.Response)
				}
				if strings.Contains(result.Thinking, "<think>") || strings.Contains(result.Thinking, "</think>") {
					t.Errorf("thinking field contains <think> tags: %q", result.Thinking[:min(len(result.Thinking), 200)])
				}
			})
		}
	})
}

